### PR TITLE
make compatible with react 14 beta

### PR DESCRIPTION
**Pull request by teosz**

### CODE REVIEW

**Comment by teosz** [comment]
#166

**Comment by skidding** [comment]
There doesn't seem to be an official changelog yet, but 0.14 seems to have some serious API changes. Did you test Cosmos with a React 0.14 project to see if everything still works?

**Comment by catalinmiron** [comment]
@skidding there is an [official doc](https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html) but as you said, there are some serious API changes.

**Comment by lapanoid** [comment]
@skidding @catalinmiron  This should be closed/changed I guess as react 14 officially released

**Comment by skidding** [comment]
> @skidding @teosz This should be closed/changed I guess as react 14 officially released

Cosmos is now a [boilerplate](https://github.com/skidding/cosmos/tree/master/webpack-boilerplate/react-0.13), so you can now upgrade your project to React 0.14.

Will include a 0.14 boilerplate as well in the future.

**Pull request closed without merging**
